### ISSUE TITLE
[1pt] Error in identify_src_bankfull.py

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1116]
I had some inundation TIFs in my FIM directory that was being overwritten and `identify_src_bankfull.py` thought it was a directory. Just add a check in there to make sure that it's a directory.

```
Estimating bankfull stage in SRCs
Writing progress to log file here: /logs/log_bankfull_indentify.log
This may take a few minutes...
Traceback (most recent call last):
  File "/foss_fim/src/identify_src_bankfull.py", line 436, in <module>
    run_prep(fim_dir, bankfull_flow_filepath, number_of_jobs, verbose, src_plot_option)
  File "/foss_fim/src/identify_src_bankfull.py", line 344, in run_prep
    for branch_id in os.listdir(huc_branches_dir):
NotADirectoryError: [Errno 20] Not a directory: '/outputs/hydrocond/01080107_2yr_fim.tif/branches'
```

**Comment by CarsonPruitt-NOAA** [comment]
I'm a regex fanatic, so I would change line 337 from this:
`huc_list = os.listdir(fim_dir)`
to this:
`huc_list = [d for d in os.listdir(fim_dir) if re.match(r'\d{8}', d)]`
