### ISSUE TITLE
[13pt] Docker build error with Whitebox

### ISSUE THREAD

**Issue by mluck** [NOAA-OWP/inundation-mapping#1181]
An error occurs when building the Docker image in the Whitebox hack introduced in #857.

## Current behavior
During `docker build --rm --no-cache --force-rm -t fim_4:4.5.2.1-whitebox .`
```
cp: cannot stat '/usr/local/lib/python3.10/dist-packages/whitebox/WhiteboxTools_linux_amd64/whitebox_tools': No such file or directory
 ---> Removed intermediate container cf6f6949b355
The command '/bin/sh -c wbox_path=/usr/local/lib/python3.10/dist-packages/whitebox/WhiteboxTools_linux_amd64 &&     wget -P $wbox_path https://www.whiteboxgeo.com/WBT_Linux/WhiteboxTools_linux_musl.zip &&     unzip -o $wbox_path/WhiteboxTools_linux_musl.zip -d $wbox_path &&     cp $wbox_path/whitebox_tools $wbox_path &&     mkdir $wbox_path/testdata' returned a non-zero code: 1
```

**Comment by mluck** [comment]
If the Whitebox hack is removed from the Dockerfile, `docker build` completes successfully but then an error occurs during `fim_pipeline.sh` in `agreedem.py`:
```
Creating AGREE DEM using 70 meter buffer 03100204 0
Downloading WhiteboxTools pre-compiled binary for first time use ...
Decompressing WhiteboxTools_linux_amd64.zip ...
WhiteboxTools package directory: /usr/local/lib/python3.10/dist-packages/whitebox
Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "/foss_fim/src/agreedem.py", line 321, in <module>
    agreedem(
  File "/foss_fim/src/agreedem.py", line 51, in agreedem
    wbt = whitebox.WhiteboxTools()
  File "/usr/local/lib/python3.10/dist-packages/whitebox/whitebox_tools.py", line 278, in __init__
    download_wbt()
  File "/usr/local/lib/python3.10/dist-packages/whitebox/whitebox_tools.py", line 157, in download_wbt
    shutil.copytree(init_img_dir, new_img_dir)
  File "/usr/lib/python3.10/shutil.py", line 557, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/whitebox/WBT/img'
Command exited with non-zero status 1
	Command being timed: "/foss_fim/src/run_unit_wb.sh"
	User time (seconds): 63.44
	System time (seconds): 11.73
	Percent of CPU this job got: 63%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:59.20
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1314520
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 464
	Minor (reclaiming a frame) page faults: 3845630
	Voluntary context switches: 9001
	Involuntary context switches: 536307
	Swaps: 0
	File system inputs: 342376
	File system outputs: 639320
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1

***** An error has occured  *****
```

**Comment by mluck** [comment]
It appears that this is an issue with a recent release of Whitebox (https://github.com/jblindsay/whitebox-tools/issues/409#issuecomment-2133675857) and that a patch has been released (https://github.com/opengeos/whitebox-python/pull/65).
