### ISSUE TITLE
[5pt] Error while running `generate_nws_lid.py`

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#1213]
Here's the command I used and the error that got thrown.

```
root@90ec45ada0b1:/data/temp/carson# python /foss_fim/tools/generate_nws_lid.py -w /data/temp/carson/nws_lid/
Retrieving metadata ..
Traversing network..
Traceback (most recent call last):
  File "/foss_fim/tools/generate_nws_lid.py", line 179, in <module>
    generate_nws_lid(**args)
  File "/foss_fim/tools/generate_nws_lid.py", line 125, in generate_nws_lid
    [to_node] = network[from_node]
KeyError: 75004300004254
```

**Comment by CarsonPruitt-NOAA** [comment]
Oh, good call. I was working off an older version. I'm re-testing now.
