### ISSUE TITLE
[3 pt] Numpy bug in inundation

### ISSUE THREAD

**Issue by erkaufman** [NOAA-OWP/inundation-mapping#1235]
When running inundation after the docker image update there was an error thrown for numpy integers. Three instances in `overlapping_inundation.py` where we should specify the bytes on numpy types. 
```
python /foss_fim/tools/inundate_mosaic_wrapper.py -y /fim-home/emma.kaufman/fim_subgrid/subgrid_hand -u 07140102 -f /fim-home/emma.kaufman/impact/benchmark_inundation_tif/erkm7/ahps_allfids_maximum_erkm7.csv -d /fim-home/emma.kaufman/impact/ahaps_test_cases_outputs/maximum_1m/erkm7_maximum_depth_1m.tif
/usr/local/lib/python3.10/dist-packages/numba/typed/typeddict.py:39: NumbaTypeSafetyWarning: unsafe cast from int64 to int32. Precision may be lost.
  return d[key]
Traceback (most recent call last):
  File "/foss_fim/tools/inundate_mosaic_wrapper.py", line 226, in <module>
    produce_mosaicked_inundation(**vars(parser.parse_args()))
  File "/foss_fim/tools/inundate_mosaic_wrapper.py", line 129, in produce_mosaicked_inundation
    mosaic_file_path = Mosaic_inundation(
  File "/foss_fim/tools/mosaic_inundation.py", line 85, in Mosaic_inundation
    remove_list = mosaic_by_unit(
  File "/foss_fim/tools/mosaic_inundation.py", line 136, in mosaic_by_unit
    overlap.merge_rasters(mosaic_output, threaded=threaded, workers=1, nodata=nodata)
  File "/foss_fim/tools/overlapping_inundation.py", line 265, in merge_rasters
    window_bounds, window_idx = self.get_window_coords()
  File "/foss_fim/tools/overlapping_inundation.py", line 144, in get_window_coords
    ).astype(np.int)
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?
```

**Comment by RobHanna-NOAA** [comment]
Not a bug.  Fix previous made in Dev and was not fully pulled in to local branch.
