### ISSUE TITLE
Errors for test_case_by_hydro_id.py

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#1240]
In attempting to run test_case_by_hydro_id.py, it threw two error near immediately.

listing_test_cases_with_updates
/data/previous_fim/fim_4_5_2_11/04300109 does not exist
projecting to 3857/fim_4_5_2_11/10280103
Traceback (most recent call last):
  File "//foss_fim/tools/test_case_by_hydro_id.py", line 302, in <module>
    csv_output = csv_output.to_crs('EPSG:3857')
  File "/usr/local/lib/python3.10/dist-packages/geopandas/geodataframe.py", line 1407, in to_crs
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)
  File "/usr/local/lib/python3.10/dist-packages/geopandas/geoseries.py", line 1170, in to_crs
    self.values.to_crs(crs=crs, epsg=epsg), index=self.index, name=self.name
  File "/usr/local/lib/python3.10/dist-packages/geopandas/array.py", line 855, in to_crs
    raise ValueError(
ValueError: Cannot transform naive geometries.  Please set a crs on the object first.

---------------
command run:

python foss_fim/tools/test_case_by_hydro_id.py -v fim_4_5_2_11 -g /data/fim_performance/fim_4_5_2_11/fim_performance_catchments.gpkg -b all

---------------
I think we have a couple of errors:
1)  Why did it try to process 04300109 as it was not processed? The script looks for all HUCs that have test case data. 
- We need to add a check that if the HUC folder does not exist in the root output folder, do not process.
- We should handle if a HUC failed to process.  When a HUC fails, it makes a copy of that HUC's log file and puts it in the /unit_erors folder. Over and above the huc folder not existing, we should pull all the file names in the unit_errors folder and see if that HUC is part of one of file names. PS. there may be zero files in that unit_errors folder if all processed correctly.

2) Look into the CRS bug above.  Remember that for non Alaska, the incoming CRS is 5070 and Alaska is 3338, so you likely just have to pick up the HUC starts with 19 and pre-set the crs before pre-projecting it or something.

3) It is also possible for a branch to fail and be trapped successfully.  I recommend that when we load up the list of branches for a HUC and it can not find the gw_catchments_reaches_filtered_addedAttributes_crosswalked_" + branches + ".gpkg, skip that branch.

**Comment by RobHanna-NOAA** [comment]
Tried on EC2 Prod 3 and made it part of the way until it got to an Alaska HUC, then errored.

performing_zonal_stats for /data/test_cases/nws_test_cases/05120204_nws/official_versions/fim_4_5_2_11/action/drei3_b0m_agreement.tif
assembling_hydroalpha_for_single_huc
performing_zonal_stats for /data/test_cases/nws_test_cases/19020302_nws/official_versions/fim_4_5_2_11/action/sxra2_b0m_agreement.tif
assembling_hydroalpha_for_single_huc
Traceback (most recent call last):
  File "//foss_fim/tools/test_case_by_hydro_id.py", line 299, in <module>
    csv_output = pd.concat(concat_df_list, sort=False)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/reshape/concat.py", line 385, in concat
    return op.get_result()
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/reshape/concat.py", line 616, in get_result
    new_data = concatenate_managers(
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/internals/concat.py", line 235, in concatenate_managers
    values = concat_compat(vals, axis=1)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/dtypes/concat.py", line 98, in concat_compat
    return cls._concat_same_type(to_concat)
  File "/usr/local/lib/python3.10/dist-packages/geopandas/array.py", line 1459, in _concat_same_type
    return GeometryArray(data, crs=_get_common_crs(to_concat))
  File "/usr/local/lib/python3.10/dist-packages/geopandas/array.py", line 1557, in _get_common_crs
    raise ValueError(
ValueError: Cannot determine common CRS for concatenation inputs, got ['NAD83 / Alaska Albers', 'NAD83 / Conus Albers']. Use `to_crs()` to transform geometries to the same CRS before merging.
Thu Aug  1 23:02:22 UTC 2024

**Comment by RobHanna-NOAA** [comment]
Matt did some testing against the FIM 4.5.4.4 code based and was successfully able to complete it without errors, no fix applied.
