### ISSUE TITLE
[5pt] Pyogrio column errors

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#1262]
During out UAT FIM 4.5.6.0 with the newest set of updated python packages, two HUCs failed both with pyogrio errors.

1. 

Copying staged wbd and .gpkg files from /data/inputs/pre_clip_huc8/20240702/02030201

-----------------------------------------------------------------
Generating Level Paths for 02030201
Traceback (most recent call last):
  File "/foss_fim/src/derive_level_paths.py", line 276, in <module>
    Derive_level_paths(**args)
  File "/foss_fim/src/derive_level_paths.py", line 200, in Derive_level_paths
    stream_network = stream_network.select_branches_intersecting_huc(
  File "/foss_fim/src/stream_branches.py", line 735, in select_branches_intersecting_huc
    self.write(out_vector_files, index=False)
  File "/foss_fim/src/stream_branches.py", line 137, in write
    self.to_file(fileName, driver=driver, layer=layer, index=index)
  File "/usr/local/lib/python3.10/dist-packages/geopandas/geodataframe.py", line 1536, in to_file
    _to_file(self, filename, driver, schema, index, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/geopandas/io/file.py", line 686, in _to_file
    _to_file_pyogrio(df, filename, driver, schema, crs, mode, metadata, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/geopandas/io/file.py", line 748, in _to_file_pyogrio
    pyogrio.write_dataframe(df, filename, driver=driver, metadata=metadata, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyogrio/geopandas.py", line 622, in write_dataframe
    write_arrow(
  File "/usr/local/lib/python3.10/dist-packages/pyogrio/raw.py", line 857, in write_arrow
    ogr_write_arrow(
  File "pyogrio/_io.pyx", line 2594, in pyogrio._io.ogr_write_arrow
  File "pyogrio/_io.pyx", line 2734, in pyogrio._io.create_fields_from_arrow_schema
pyogrio.errors.FieldError: Error while creating field from Arrow for field 7 with name 'gages' and type n (Type 'n' for field gages is not supported.).
Command exited with non-zero status 1
	Command being timed: "/foss_fim/src/run_unit_wb.sh"
	User time (seconds): 2.20

2. 
Generating Level Paths for 21010005
Traceback (most recent call last):
  File "/foss_fim/src/derive_level_paths.py", line 276, in <module>
    Derive_level_paths(**args)
  File "/foss_fim/src/derive_level_paths.py", line 165, in Derive_level_paths
    catchments.to_file(catchments_outfile, index=False, driver="GPKG")
  File "/usr/local/lib/python3.10/dist-packages/geopandas/geodataframe.py", line 1536, in to_file
    _to_file(self, filename, driver, schema, index, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/geopandas/io/file.py", line 686, in _to_file
    _to_file_pyogrio(df, filename, driver, schema, crs, mode, metadata, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/geopandas/io/file.py", line 748, in _to_file_pyogrio
    pyogrio.write_dataframe(df, filename, driver=driver, metadata=metadata, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyogrio/geopandas.py", line 622, in write_dataframe
    write_arrow(
  File "/usr/local/lib/python3.10/dist-packages/pyogrio/raw.py", line 857, in write_arrow
    ogr_write_arrow(
  File "pyogrio/_io.pyx", line 2594, in pyogrio._io.ogr_write_arrow
  File "pyogrio/_io.pyx", line 2734, in pyogrio._io.create_fields_from_arrow_schema
pyogrio.errors.FieldError: Error while creating field from Arrow for field 1 with name 'AreaSqKM' and type n (Type 'n' for field AreaSqKM is not supported.).
Command exited with non-zero status 1
	Command being timed: "/foss_fim/src/run_unit_wb.sh"

**Comment by RobHanna-NOAA** [comment]
Is that a spam in the comment above.. highly suspicious
