### ISSUE TITLE
[5pt] Run_by_unit does take multiple huc comma delimited

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#519]
This functionality existed in FIM3 in its version (as part of fim_run.sh)

Error message:
- fails on multiple commented hucs
Traceback (most recent call last):
File "/foss_fim/src/check_huc_inputs.py", line 61, in
check_hucs(**args)
File "/foss_fim/src/check_huc_inputs.py", line 48, in check_hucs
__check_for_membership(hucs,accepted_hucs)
File "/foss_fim/src/check_huc_inputs.py", line 41, in __check_for_membership
raise KeyError("HUC {} not found in available inputs. Edit HUC inputs or acquire datasets and try again".format(huc))
KeyError: 'HUC 12030107,06030002,03070105,05010009 not found in available inputs. Edit HUC inputs or acquire datasets and try again'

Note: Documentation in the run_by_unit.sh suggest it should work.

Note: This might have not worked in FIM3

**Comment by RobHanna-NOAA** [comment]
In testing, it was discovered that a comma delimited is not supposed to work. However it does work as space delimited with a set of double quotes around the whole thing.  ie ) -u "07080101 05030204 13030202" (will work).  All that is required is to upgrade the "help" notes for run_by_unit.sh.
