### ISSUE TITLE
[5pt] Branch pruning errors

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#677]
During a BED run of v4.0.9.1, there were a few HUCs that had non-zero exit codes associated with the branch pruning process.

**Comment by CarsonPruitt-NOAA** [comment]
```
##########################################################################
Generating Level Paths for 12090203
##########################################################################
Sat Sep 10 09:10:23 UTC 2022
Deriving level paths ...
Loading stream network ...
Deriving nodes ...
Deriving outlets ...
Deriving inlets ...
Upstream and downstream dictionaries: 100%|██████████| 100/100 [00:00<00:00, 1196.24it/s]
Arbolate sums: 100%|██████████| 100/100 [00:00<00:00, 2591.57it/s]
Stream branches: 101it [00:00, 407.58it/s]
Removing stream branches without catchments ...
Writing stream branches ...
Trimming stream branches in waterbodies ...
Dissolving by branch ...
Merging mult-part geoms: 100%|██████████| 7/7 [00:00<00:00, 832.25it/s]
Writing dissolved branches ...
Traceback (most recent call last):
  File "fiona/_shim.pyx", line 74, in fiona._shim.gdal_open_vector
  File "fiona/_err.pyx", line 291, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_OpenFailedError: /data/outputs/fim_4_0_9_1/12090203/nwm_lakes_proj_subset.gpkg: No such file or directory                                               [0/738]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/foss_fim/src/gms/derive_level_paths.py", line 193, in <module>
    Derive_level_paths(**args)
  File "/foss_fim/src/gms/derive_level_paths.py", line 158, in Derive_level_paths
    stream_network = stream_network.remove_branches_in_waterbodies(waterbodies=waterbodies,
  File "/foss_fim/src/gms/stream_branches.py", line 533, in remove_branches_in_waterbodies
    waterbodies = gpd.read_file(waterbodies)
  File "/usr/local/lib/python3.8/dist-packages/geopandas/io/file.py", line 96, in _read_file
    with reader(path_or_bytes, **kwargs) as features:
  File "/usr/local/lib/python3.8/dist-packages/fiona/env.py", line 400, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/fiona/__init__.py", line 256, in open
    c = Collection(path, mode, driver=driver, encoding=encoding,
  File "/usr/local/lib/python3.8/dist-packages/fiona/collection.py", line 164, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 536, in fiona.ogrext.Session.start
  File "fiona/_shim.pyx", line 81, in fiona._shim.gdal_open_vector
fiona.errors.DriverError: /data/outputs/fim_4_0_9_1/12090203/nwm_lakes_proj_subset.gpkg: No such file or directory
```

**Comment by mluck** [comment]
Both of these errors have been fixed in the latest commits to `dev-prune-lake-branches`. The bug still remaining is that the fix for the first error above still doesn't completely resolve the issue that the branch dissolve process doesn't join the upper (dashed red) portion of the branch to the lower (blue) portion of the same branch (segment 2674880) because the segments in the waterbody have been removed because of the attribute error so currently the branch extends only up to the lake.
![image](https://user-images.githubusercontent.com/6616694/189704089-c6f0a641-e076-4b83-8de9-b50a56f2b85c.png)

**Comment by mluck** [comment]
The attributes in [From_Node, To_Node] seem to be correct so switching from [ID, to] fixed the remaining issue.
<img width="423" alt="image" src="https://user-images.githubusercontent.com/6616694/189750657-bf59e219-c601-4dc4-b3b3-9af6823819ff.png">
