### ISSUE TITLE
[8pt] Source column has None values in usgs_gage_crosswalk.py

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#986]
```
-----------------------------------------------------------------
USGS Crosswalk 13080002 0
Tue Sep  5 15:52:31 UTC 2023
5 gages in branch 0
Traceback (most recent call last):
  File "/foss_fim/src/usgs_gage_crosswalk.py", line 150, in <module>
    gage_crosswalk.run_crosswalk(input_catchment_filename, input_flows_filename, dem_filename, dem_adj_filename, output_directory)
  File "/foss_fim/src/usgs_gage_crosswalk.py", line 62, in run_crosswalk
    self.write(output_directory)
  File "/foss_fim/src/usgs_gage_crosswalk.py", line 104, in write
    elev_table.source = elev_table.source.apply(str.lower)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/series.py", line 4630, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/apply.py", line 1025, in apply
    return self.apply_standard()
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/apply.py", line 1076, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2834, in pandas._libs.lib.map_infer
TypeError: descriptor 'lower' for 'str' objects doesn't apply to a 'NoneType' object
Command exited with non-zero status 1
        Command being timed: "/foss_fim/src/run_unit_wb.sh"
        User time (seconds): 3141.24
        System time (seconds): 277.93
        Percent of CPU this job got: 106%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 53:16.14
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 12847372
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 3997
        Minor (reclaiming a frame) page faults: 86896418
        Voluntary context switches: 148132
        Involuntary context switches: 54234
        Swaps: 0
        File system inputs: 5230816
        File system outputs: 53523544
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 1

***** An error has occured  *****
```

**Comment by CarsonPruitt-NOAA** [comment]
The `source` is defined [here](https://github.com/NOAA-OWP/inundation-mapping/blob/fa0aa48750b9ac19683b971981be0ddc9e95525a/src/usgs_gage_unit_setup.py#L26) in `src/usgs_gage_unit_setup.py`. For some reason, it appears that AHPS sites that are not USGS gages are not getting loaded correctly. The location_id is being filled with bogus lids, which I think is causing a bad WRDS call.


![Image](https://github.com/NOAA-OWP/inundation-mapping/assets/90792257/0eddd19b-78c0-49a4-a570-4ab0b2669d59)
