### ISSUE TITLE
[1 pt] Unit error thrown from `src/stream_branches.py`

### ISSUE THREAD

**Issue by robgpita-noaa** [NOAA-OWP/inundation-mapping#991]
After final processing of the BED domain using `fim_4_4_0_1`, two new unit errors with Exit code 1 were revealed. 

## Current behavior

Stacktrace from `/dev_fim_share/foss_fim/previous_fim/fim_4_4_0_1/unit_errors/`  `09010004_unit.log` & `10050004_unit.log`:

```
-----------------------------------------------------------------
Generating Level Paths for 10050004
Upstream and downstream dictionaries: 100%|██████████| 515/515 [00:00<00:00, 1435.90it/s]
/foss_fim/src/stream_branches.py:533: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  int(tmp_self.To_Node[tmp_self.From_Node.astype(int) == upstream_ID])
/foss_fim/src/stream_branches.py:539: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_self.drop(
/foss_fim/src/stream_branches.py:533: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  int(tmp_self.To_Node[tmp_self.From_Node.astype(int) == upstream_ID])
/foss_fim/src/stream_branches.py:539: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_self.drop(
/foss_fim/src/stream_branches.py:533: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  int(tmp_self.To_Node[tmp_self.From_Node.astype(int) == upstream_ID])
/foss_fim/src/stream_branches.py:539: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_self.drop(
/foss_fim/src/stream_branches.py:533: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  int(tmp_self.To_Node[tmp_self.From_Node.astype(int) == upstream_ID])

Traceback (most recent call last):
  File "/foss_fim/src/derive_level_paths.py", line 312, in <module>
    Derive_level_paths(**args)
  File "/foss_fim/src/derive_level_paths.py", line 208, in Derive_level_paths
    branch_inlets = stream_network.derive_inlet_points_by_feature(
  File "/foss_fim/src/stream_branches.py", line 371, in derive_inlet_points_by_feature
    feature_inlet_point = Point(row.geometry.coords[inlet_linestring_index])
  File "/usr/local/lib/python3.8/dist-packages/shapely/geometry/base.py", line 910, in coords
    raise NotImplementedError(
NotImplementedError: Sub-geometries may have coordinate sequences, but multi-part geometries do not

-----------------------------------------------------------------
Generating Level Paths for 09010004
Thu Sep  7 19:14:47 UTC 2023
Upstream and downstream dictionaries: 100%|██████████| 165/165 [00:00<00:00, 887.09it/s]
/foss_fim/src/stream_branches.py:503: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_self.drop(
/foss_fim/src/stream_branches.py:503: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_self.drop(
/foss_fim/src/stream_branches.py:503: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_self.drop(

Traceback (most recent call last):
  File "/foss_fim/src/derive_level_paths.py", line 312, in <module>
    Derive_level_paths(**args)
  File "/foss_fim/src/derive_level_paths.py", line 208, in Derive_level_paths
    branch_inlets = stream_network.derive_inlet_points_by_feature(
  File "/foss_fim/src/stream_branches.py", line 371, in derive_inlet_points_by_feature
    feature_inlet_point = Point(row.geometry.coords[inlet_linestring_index])
  File "/usr/local/lib/python3.8/dist-packages/shapely/geometry/base.py", line 910, in coords
    raise NotImplementedError(
NotImplementedError: Sub-geometries may have coordinate sequences, but multi-part geometries do not
```

## Expected behavior

No unit errors being thrown.

**Comment by mluck** [comment]
Those errors are occurring because a branch in each of those HUCs contains `MultiLineString` geometries instead of `LineString`s. I've got a feature branch that patches that error.

In the case of HUC 09010004, this happens due to clipping the NWM stream layer inside the buffered WBD which then re-enters the HUC at a different point. When the level paths are created, those segments are automatically joined (red lines).
<img width="458" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/56ca22cf-0a82-4109-9399-c975992eb6a0">
